""" Unit test coverage for imgur_populator
"""
import configparser
from unittest import TestCase
from unittest.mock import patch, sentinel, MagicMock, Mock

import mysql

import imgur_populator


class TestImgurPopulator(TestCase):
    def setUp(self):
        # Load the configuration file
        self.config = configparser.ConfigParser()
        self.config.read("./imgur.conf")
        self.config['imgur']['api_endpoint'] = '["http://example.com/api_endpoint"]'

        # Mock out the imgur API
        patcher = patch('imgur_populator.ImgurAPI.fetch_viral_images')
        self.MockFetchViralImages = patcher.start()
        self.addCleanup(patcher.stop)

        # Mock out the database
        patcher = patch('mysql.connector.connect')
        self.MockDatabase = patcher.start()
        self.MockCursor = Mock()
        self.MockCursor.rowcount = 1
        self.MockConnection = Mock()
        self.MockConnection.cursor.return_value = self.MockCursor
        self.MockDatabase.return_value = self.MockConnection
        self.addCleanup(patcher.stop)

    def test_ok(self):
        # Setup
        populator = imgur_populator.ImgurPopulator(self.config)

        # This sample data was pulled live from the Imgur API
        # It contains 104 "valid" images
        self.MockFetchViralImages.return_value = [{
                                                  'title': 'Nothing worse than waking up on a Sunday morning, and having to clean up the carnage left behind after another wild Saturday night.',
                                                  'image_url': 'http://i.imgur.com/2ttVNms.jpg',
                                                  'page_url': 'http://imgur.com/gallery/2ttVNms',
                                                  'thumbnail_url': 'http://i.imgur.com/2ttVNmsm.jpg'}, {
                                                  'title': "4.5 years after being told by a team of doctors that I'd probably never move anything below my shoulders again, I finally got to take this pic.",
                                                  'image_url': 'http://i.imgur.com/CB7eLyt.jpg',
                                                  'page_url': 'http://imgur.com/gallery/CB7eLyt',
                                                  'thumbnail_url': 'http://i.imgur.com/CB7eLytm.jpg'},
                                                  {'title': 'This is the end.',
                                                   'image_url': 'http://i.imgur.com/0tKpikW.jpg',
                                                   'page_url': 'http://imgur.com/gallery/0tKpikW',
                                                   'thumbnail_url': 'http://i.imgur.com/0tKpikWm.jpg'},
                                                  {'title': 'Way better than lemonade',
                                                   'image_url': 'http://i.imgur.com/AVBmbVi.jpg',
                                                   'page_url': 'http://imgur.com/gallery/AVBmbVi',
                                                   'thumbnail_url': 'http://i.imgur.com/AVBmbVim.jpg'},
                                                  {'title': 'The one who gets shot pays the bill.',
                                                   'image_url': 'http://i.imgur.com/sof10tP.jpg',
                                                   'page_url': 'http://imgur.com/gallery/sof10tP',
                                                   'thumbnail_url': 'http://i.imgur.com/sof10tPm.jpg'},
                                                  {'title': 'Lord, imagine the pizza this thing came with',
                                                   'image_url': 'http://i.imgur.com/tkeHnkn.jpg',
                                                   'page_url': 'http://imgur.com/gallery/tkeHnkn',
                                                   'thumbnail_url': 'http://i.imgur.com/tkeHnknm.jpg'},
                                                  {'title': '*groan*', 'image_url': 'http://i.imgur.com/OMqs78a.png',
                                                   'page_url': 'http://imgur.com/gallery/OMqs78a',
                                                   'thumbnail_url': 'http://i.imgur.com/OMqs78am.png'}, {
                                                  'title': 'Doing two weeks in Texas and got questioned about my "gang" tattoos at PT this morning.',
                                                  'image_url': 'http://i.imgur.com/xpmhVOY.jpg',
                                                  'page_url': 'http://imgur.com/gallery/xpmhVOY',
                                                  'thumbnail_url': 'http://i.imgur.com/xpmhVOYm.jpg'},
                                                  {'title': 'The best thing ever while growing up',
                                                   'image_url': 'http://i.imgur.com/4yLJnTd.jpg',
                                                   'page_url': 'http://imgur.com/gallery/4yLJnTd',
                                                   'thumbnail_url': 'http://i.imgur.com/4yLJnTdm.jpg'},
                                                  {'title': 'Other ways to say ...',
                                                   'image_url': 'http://i.imgur.com/6pR3YCO.jpg',
                                                   'page_url': 'http://imgur.com/gallery/6pR3YCO',
                                                   'thumbnail_url': 'http://i.imgur.com/6pR3YCOm.jpg'},
                                                  {'title': 'Men will be men',
                                                   'image_url': 'http://i.imgur.com/7QGD1S4.jpg',
                                                   'page_url': 'http://imgur.com/gallery/7QGD1S4',
                                                   'thumbnail_url': 'http://i.imgur.com/7QGD1S4m.jpg'},
                                                  {'title': 'Classic, A.',
                                                   'image_url': 'http://i.imgur.com/XsKUs0H.jpg',
                                                   'page_url': 'http://imgur.com/gallery/XsKUs0H',
                                                   'thumbnail_url': 'http://i.imgur.com/XsKUs0Hm.jpg'}, {
                                                  'title': 'You may remember Charlie the tortoise hibernating in the fridge? Well here he is enjoying summer after a successful escape from his bath..',
                                                  'image_url': 'http://i.imgur.com/6yfhiVV.jpg',
                                                  'page_url': 'http://imgur.com/gallery/6yfhiVV',
                                                  'thumbnail_url': 'http://i.imgur.com/6yfhiVVm.jpg'},
                                                  {'title': ' Tonight is the Night!',
                                                   'image_url': 'http://i.imgur.com/bc65yRi.png',
                                                   'page_url': 'http://imgur.com/gallery/bc65yRi',
                                                   'thumbnail_url': 'http://i.imgur.com/bc65yRim.png'},
                                                  {'title': 'This week in science',
                                                   'image_url': 'http://i.imgur.com/MY60SYK.png',
                                                   'page_url': 'http://imgur.com/gallery/MY60SYK',
                                                   'thumbnail_url': 'http://i.imgur.com/MY60SYKm.png'}, {
                                                  'title': 'We saved a turtle crossing the street. The turtle decided to thank us in a odd way.',
                                                  'image_url': 'http://i.imgur.com/VDOLVFd.jpg',
                                                  'page_url': 'http://imgur.com/gallery/VDOLVFd',
                                                  'thumbnail_url': 'http://i.imgur.com/VDOLVFdm.jpg'},
                                                  {'title': 'I\'m really enjoying "Astonishing X-Men" right now',
                                                   'image_url': 'http://i.imgur.com/ZfyhbA5.png',
                                                   'page_url': 'http://imgur.com/gallery/ZfyhbA5',
                                                   'thumbnail_url': 'http://i.imgur.com/ZfyhbA5m.png'}, {
                                                  'title': 'My friend took a photo of her house every 10 seconds for 2 hours the other evening. This was the result.',
                                                  'image_url': 'http://i.imgur.com/deqQyFV.jpg',
                                                  'page_url': 'http://imgur.com/gallery/deqQyFV',
                                                  'thumbnail_url': 'http://i.imgur.com/deqQyFVm.jpg'},
                                                  {'title': 'Hi, Imgur Team!',
                                                   'image_url': 'http://i.imgur.com/UvpwFEw.png',
                                                   'page_url': 'http://imgur.com/gallery/UvpwFEw',
                                                   'thumbnail_url': 'http://i.imgur.com/UvpwFEwm.png'}, {
                                                  'title': '"Chancho. When you are a man sometimes you wear stretchy pants in your room. It\'s for fun."',
                                                  'image_url': 'http://i.imgur.com/RAwKCqZ.jpg',
                                                  'page_url': 'http://imgur.com/gallery/RAwKCqZ',
                                                  'thumbnail_url': 'http://i.imgur.com/RAwKCqZm.jpg'},
                                                  {'title': 'Try me.', 'image_url': 'http://i.imgur.com/GdpRhn2.jpg',
                                                   'page_url': 'http://imgur.com/gallery/GdpRhn2',
                                                   'thumbnail_url': 'http://i.imgur.com/GdpRhn2m.jpg'},
                                                  {'title': 'These things happen.',
                                                   'image_url': 'http://i.imgur.com/ft0yvpD.jpg',
                                                   'page_url': 'http://imgur.com/gallery/ft0yvpD',
                                                   'thumbnail_url': 'http://i.imgur.com/ft0yvpDm.jpg'},
                                                  {'title': 'Trolling lvl. Turtle',
                                                   'image_url': 'http://i.imgur.com/T8lOlbI.jpg',
                                                   'page_url': 'http://imgur.com/gallery/T8lOlbI',
                                                   'thumbnail_url': 'http://i.imgur.com/T8lOlbIm.jpg'},
                                                  {'title': ' M&M color distribution',
                                                   'image_url': 'http://i.imgur.com/6XLv27D.jpg',
                                                   'page_url': 'http://imgur.com/gallery/6XLv27D',
                                                   'thumbnail_url': 'http://i.imgur.com/6XLv27Dm.jpg'},
                                                  {'title': 'Starting my New life as a Nanny',
                                                   'image_url': 'http://i.imgur.com/FyvegRR.jpg',
                                                   'page_url': 'http://imgur.com/gallery/FyvegRR',
                                                   'thumbnail_url': 'http://i.imgur.com/FyvegRRm.jpg'},
                                                  {'title': ' Happy Game of Thrones day, Internet!',
                                                   'image_url': 'http://i.imgur.com/Db9xTnm.jpg',
                                                   'page_url': 'http://imgur.com/gallery/Db9xTnm',
                                                   'thumbnail_url': 'http://i.imgur.com/Db9xTnmm.jpg'},
                                                  {'title': 'I found this little guy in my pool',
                                                   'image_url': 'http://i.imgur.com/FwspQsb.png',
                                                   'page_url': 'http://imgur.com/gallery/FwspQsb',
                                                   'thumbnail_url': 'http://i.imgur.com/FwspQsbm.png'}, {
                                                  'title': "A man begging for his wife's forgiveness inside Divorce Court. Chicago, 1948. ",
                                                  'image_url': 'http://i.imgur.com/1uxhBhm.jpg',
                                                  'page_url': 'http://imgur.com/gallery/1uxhBhm',
                                                  'thumbnail_url': 'http://i.imgur.com/1uxhBhmm.jpg'},
                                                  {'title': 'Ladies and Gentlemen, Stephen King,',
                                                   'image_url': 'http://i.imgur.com/L0UETbS.jpg',
                                                   'page_url': 'http://imgur.com/gallery/L0UETbS',
                                                   'thumbnail_url': 'http://i.imgur.com/L0UETbSm.jpg'}, {
                                                  'title': 'The teenage girls who were raped, murdered and left hanging from a mango tree in the case which has shocked India',
                                                  'image_url': 'http://i.imgur.com/91mhBIU.jpg',
                                                  'page_url': 'http://imgur.com/gallery/91mhBIU',
                                                  'thumbnail_url': 'http://i.imgur.com/91mhBIUm.jpg'},
                                                  {'title': 'Anyone looking for a job?',
                                                   'image_url': 'http://i.imgur.com/0fSzu6E.jpg',
                                                   'page_url': 'http://imgur.com/gallery/0fSzu6E',
                                                   'thumbnail_url': 'http://i.imgur.com/0fSzu6Em.jpg'},
                                                  {'title': '/fit/izen on fat people',
                                                   'image_url': 'http://i.imgur.com/8Qmq4d8.jpg',
                                                   'page_url': 'http://imgur.com/gallery/8Qmq4d8',
                                                   'thumbnail_url': 'http://i.imgur.com/8Qmq4d8m.jpg'},
                                                  {'title': 'A prayer', 'image_url': 'http://i.imgur.com/Jw1rr3x.jpg',
                                                   'page_url': 'http://imgur.com/gallery/Jw1rr3x',
                                                   'thumbnail_url': 'http://i.imgur.com/Jw1rr3xm.jpg'}, {
                                                  'title': 'My friend was paid $1,000+ to shave her head. She donated the money to cancer research and donated the hair to make wigs for cancer patients!',
                                                  'image_url': 'http://i.imgur.com/rPJ9PMR.jpg',
                                                  'page_url': 'http://imgur.com/gallery/rPJ9PMR',
                                                  'thumbnail_url': 'http://i.imgur.com/rPJ9PMRm.jpg'},
                                                  {'title': 'Happy birthday to the great man!',
                                                   'image_url': 'http://i.imgur.com/q5PU1RJ.jpg',
                                                   'page_url': 'http://imgur.com/gallery/q5PU1RJ',
                                                   'thumbnail_url': 'http://i.imgur.com/q5PU1RJm.jpg'},
                                                  {'title': 'Golden Not Retrieving.',
                                                   'image_url': 'http://i.imgur.com/dBHYENI.jpg',
                                                   'page_url': 'http://imgur.com/gallery/dBHYENI',
                                                   'thumbnail_url': 'http://i.imgur.com/dBHYENIm.jpg'}, {
                                                  'title': ' My prediction of how Game of Thrones will end, based on current events',
                                                  'image_url': 'http://i.imgur.com/1wBaCnD.png',
                                                  'page_url': 'http://imgur.com/gallery/1wBaCnD',
                                                  'thumbnail_url': 'http://i.imgur.com/1wBaCnDm.png'},
                                                  {'title': 'Was watching Linus when...',
                                                   'image_url': 'http://i.imgur.com/ca2eARK.png',
                                                   'page_url': 'http://imgur.com/gallery/ca2eARK',
                                                   'thumbnail_url': 'http://i.imgur.com/ca2eARKm.png'},
                                                  {'title': 'Dads will understand...',
                                                   'image_url': 'http://i.imgur.com/VpOFmOi.jpg',
                                                   'page_url': 'http://imgur.com/gallery/VpOFmOi',
                                                   'thumbnail_url': 'http://i.imgur.com/VpOFmOim.jpg'},
                                                  {'title': 'Goddamn, I cried laughing at this.',
                                                   'image_url': 'http://i.imgur.com/kE7adyW.jpg',
                                                   'page_url': 'http://imgur.com/gallery/kE7adyW',
                                                   'thumbnail_url': 'http://i.imgur.com/kE7adyWm.jpg'}, {
                                                  'title': 'Just finished serving this great nation to arrive home and find out I can marry the man I spent the last 9 years with.',
                                                  'image_url': 'http://i.imgur.com/VZk60RR.jpg',
                                                  'page_url': 'http://imgur.com/gallery/VZk60RR',
                                                  'thumbnail_url': 'http://i.imgur.com/VZk60RRm.jpg'}, {
                                                  'title': "Steve Irwin and 'Harriet' the tortoise who died in 2006 at the age of 176. Harriet was a pet of Charles Darwin in 1835.",
                                                  'image_url': 'http://i.imgur.com/ZZOlAT6.jpg',
                                                  'page_url': 'http://imgur.com/gallery/ZZOlAT6',
                                                  'thumbnail_url': 'http://i.imgur.com/ZZOlAT6m.jpg'},
                                                  {'title': 'My Daughter at the Aquarium',
                                                   'image_url': 'http://i.imgur.com/wx5szcF.jpg',
                                                   'page_url': 'http://imgur.com/gallery/wx5szcF',
                                                   'thumbnail_url': 'http://i.imgur.com/wx5szcFm.jpg'},
                                                  {'title': '.', 'image_url': 'http://i.imgur.com/y7zMxJf.jpg',
                                                   'page_url': 'http://imgur.com/gallery/y7zMxJf',
                                                   'thumbnail_url': 'http://i.imgur.com/y7zMxJfm.jpg'},
                                                  {'title': "This is not a gif; it's just a moving picture",
                                                   'image_url': 'http://i.imgur.com/S4YPEKk.jpg',
                                                   'page_url': 'http://imgur.com/gallery/S4YPEKk',
                                                   'thumbnail_url': 'http://i.imgur.com/S4YPEKkm.jpg'}, {
                                                  'title': 'My foreign mom texted me "I saw Hog Hogun at Frankfurt airport and took a selfie with him"',
                                                  'image_url': 'http://i.imgur.com/FJmppW6.jpg',
                                                  'page_url': 'http://imgur.com/gallery/FJmppW6',
                                                  'thumbnail_url': 'http://i.imgur.com/FJmppW6m.jpg'},
                                                  {'title': 'I just had to look it up...',
                                                   'image_url': 'http://i.imgur.com/lt11a5r.png',
                                                   'page_url': 'http://imgur.com/gallery/lt11a5r',
                                                   'thumbnail_url': 'http://i.imgur.com/lt11a5rm.png'},
                                                  {'title': "Yup, it's that time of year again.",
                                                   'image_url': 'http://i.imgur.com/o2IMExa.jpg',
                                                   'page_url': 'http://imgur.com/gallery/o2IMExa',
                                                   'thumbnail_url': 'http://i.imgur.com/o2IMExam.jpg'},
                                                  {'title': 'Aztec Dancer',
                                                   'image_url': 'http://i.imgur.com/Ekawxi4.jpg',
                                                   'page_url': 'http://imgur.com/gallery/Ekawxi4',
                                                   'thumbnail_url': 'http://i.imgur.com/Ekawxi4m.jpg'},
                                                  {'title': 'This just popped up in my newsfeed',
                                                   'image_url': 'http://i.imgur.com/z60U290.jpg',
                                                   'page_url': 'http://imgur.com/gallery/z60U290',
                                                   'thumbnail_url': 'http://i.imgur.com/z60U290m.jpg'},
                                                  {'title': 'Bill Gates is an amazingly humble man',
                                                   'image_url': 'http://i.imgur.com/DTDsH0P.jpg',
                                                   'page_url': 'http://imgur.com/gallery/DTDsH0P',
                                                   'thumbnail_url': 'http://i.imgur.com/DTDsH0Pm.jpg'},
                                                  {'title': 'Found a perfect spot to escape the afternoon sun.',
                                                   'image_url': 'http://i.imgur.com/AMkMtfQ.jpg',
                                                   'page_url': 'http://imgur.com/gallery/AMkMtfQ',
                                                   'thumbnail_url': 'http://i.imgur.com/AMkMtfQm.jpg'},
                                                  {'title': 'B.I.T.C.H.', 'image_url': 'http://i.imgur.com/0OZOkos.jpg',
                                                   'page_url': 'http://imgur.com/gallery/0OZOkos',
                                                   'thumbnail_url': 'http://i.imgur.com/0OZOkosm.jpg'},
                                                  {'title': 'Weight loss journey so far. 308 lbs to 170 in 17 months',
                                                   'image_url': 'http://i.imgur.com/DriOdab.jpg',
                                                   'page_url': 'http://imgur.com/gallery/DriOdab',
                                                   'thumbnail_url': 'http://i.imgur.com/DriOdabm.jpg'},
                                                  {'title': 'Mr. Rogers', 'image_url': 'http://i.imgur.com/cMICmuq.jpg',
                                                   'page_url': 'http://imgur.com/gallery/cMICmuq',
                                                   'thumbnail_url': 'http://i.imgur.com/cMICmuqm.jpg'}, {
                                                  'title': 'I had to use the bathroom on our walk today, so Tucker got to go inside the ladies room for the first time.',
                                                  'image_url': 'http://i.imgur.com/b4pX9eQ.jpg',
                                                  'page_url': 'http://imgur.com/gallery/b4pX9eQ',
                                                  'thumbnail_url': 'http://i.imgur.com/b4pX9eQm.jpg'}, {
                                                  'title': 'She reminds you of Stuart? I think shes going for the Simple Jack look.',
                                                  'image_url': 'http://i.imgur.com/BIj9DdI.jpg',
                                                  'page_url': 'http://imgur.com/gallery/BIj9DdI',
                                                  'thumbnail_url': 'http://i.imgur.com/BIj9DdIm.jpg'},
                                                  {'title': 'Brazil', 'image_url': 'http://i.imgur.com/Ceh5Wrn.jpg',
                                                   'page_url': 'http://imgur.com/gallery/Ceh5Wrn',
                                                   'thumbnail_url': 'http://i.imgur.com/Ceh5Wrnm.jpg'}, {
                                                  'title': "UK garden center grows Britain's first black tomatoes which contains anthocyanins, an oxidant believed to help fight cancer, diabetes and obesity",
                                                  'image_url': 'http://i.imgur.com/9xLD8eT.jpg',
                                                  'page_url': 'http://imgur.com/gallery/9xLD8eT',
                                                  'thumbnail_url': 'http://i.imgur.com/9xLD8eTm.jpg'}, {
                                                  'title': 'Today, my 6 year old sister in law asked who the man with the little arms and legs was. Now I cannot unsee it.',
                                                  'image_url': 'http://i.imgur.com/dGiGD80.jpg',
                                                  'page_url': 'http://imgur.com/gallery/dGiGD80',
                                                  'thumbnail_url': 'http://i.imgur.com/dGiGD80m.jpg'},
                                                  {'title': 'Sent my husband to buy a baby shower gift bag. Dammit.',
                                                   'image_url': 'http://i.imgur.com/medDnz3.jpg',
                                                   'page_url': 'http://imgur.com/gallery/medDnz3',
                                                   'thumbnail_url': 'http://i.imgur.com/medDnz3m.jpg'}, {
                                                  'title': 'I caught a picture this tree trying to crawl into the water',
                                                  'image_url': 'http://i.imgur.com/VWnZ9Vb.jpg',
                                                  'page_url': 'http://imgur.com/gallery/VWnZ9Vb',
                                                  'thumbnail_url': 'http://i.imgur.com/VWnZ9Vbm.jpg'},
                                                  {'title': "Stinkin' racists...",
                                                   'image_url': 'http://i.imgur.com/lza3DGE.png',
                                                   'page_url': 'http://imgur.com/gallery/lza3DGE',
                                                   'thumbnail_url': 'http://i.imgur.com/lza3DGEm.png'},
                                                  {'title': 'Parents burn',
                                                   'image_url': 'http://i.imgur.com/5irbrwT.jpg',
                                                   'page_url': 'http://imgur.com/gallery/5irbrwT',
                                                   'thumbnail_url': 'http://i.imgur.com/5irbrwTm.jpg'},
                                                  {'title': 'And we wonder why no one visits us',
                                                   'image_url': 'http://i.imgur.com/WesPTUl.jpg',
                                                   'page_url': 'http://imgur.com/gallery/WesPTUl',
                                                   'thumbnail_url': 'http://i.imgur.com/WesPTUlm.jpg'}, {
                                                  'title': 'went to a katy perry concert, I think this was taken at the right time.',
                                                  'image_url': 'http://i.imgur.com/88Ag08s.jpg',
                                                  'page_url': 'http://imgur.com/gallery/88Ag08s',
                                                  'thumbnail_url': 'http://i.imgur.com/88Ag08sm.jpg'},
                                                  {'title': 'Welcome To Fabulous Las Vegas, Nevada!',
                                                   'image_url': 'http://i.imgur.com/OJfxY4H.jpg',
                                                   'page_url': 'http://imgur.com/gallery/OJfxY4H',
                                                   'thumbnail_url': 'http://i.imgur.com/OJfxY4Hm.jpg'},
                                                  {'title': 'Look at who I found on my hike today!',
                                                   'image_url': 'http://i.imgur.com/EWyYXAN.jpg',
                                                   'page_url': 'http://imgur.com/gallery/EWyYXAN',
                                                   'thumbnail_url': 'http://i.imgur.com/EWyYXANm.jpg'},
                                                  {'title': "She's a looker",
                                                   'image_url': 'http://i.imgur.com/bOORCMW.png',
                                                   'page_url': 'http://imgur.com/gallery/bOORCMW',
                                                   'thumbnail_url': 'http://i.imgur.com/bOORCMWm.png'}, {
                                                  'title': 'This is actually disgusting. Forcing a child who doesn’t know any better to do something just because you believe in it. No child should be made to wear Crocs in public please stop this.',
                                                  'image_url': 'http://i.imgur.com/41ba59I.jpg',
                                                  'page_url': 'http://imgur.com/gallery/41ba59I',
                                                  'thumbnail_url': 'http://i.imgur.com/41ba59Im.jpg'},
                                                  {'title': "I don't know man..",
                                                   'image_url': 'http://i.imgur.com/wbKQtLf.jpg',
                                                   'page_url': 'http://imgur.com/gallery/wbKQtLf',
                                                   'thumbnail_url': 'http://i.imgur.com/wbKQtLfm.jpg'}, {
                                                  'title': 'I started to shave my head and got about halfway done when my clippers died. I have to be somewhere in twenty minutes. I present to you the only hat that I own.',
                                                  'image_url': 'http://i.imgur.com/R1F95NA.jpg',
                                                  'page_url': 'http://imgur.com/gallery/R1F95NA',
                                                  'thumbnail_url': 'http://i.imgur.com/R1F95NAm.jpg'},
                                                  {'title': 'The rug in this bar is painted on.',
                                                   'image_url': 'http://i.imgur.com/dn88F4l.jpg',
                                                   'page_url': 'http://imgur.com/gallery/dn88F4l',
                                                   'thumbnail_url': 'http://i.imgur.com/dn88F4lm.jpg'},
                                                  {'title': 'Old but gold: the Huey Hog helicopter',
                                                   'image_url': 'http://i.imgur.com/sasDIKu.jpg',
                                                   'page_url': 'http://imgur.com/gallery/sasDIKu',
                                                   'thumbnail_url': 'http://i.imgur.com/sasDIKum.jpg'},
                                                  {'title': 'I finally figured out who miley reminds me of',
                                                   'image_url': 'http://i.imgur.com/6AQL6at.png',
                                                   'page_url': 'http://imgur.com/gallery/6AQL6at',
                                                   'thumbnail_url': 'http://i.imgur.com/6AQL6atm.png'},
                                                  {'title': 'So annoying...',
                                                   'image_url': 'http://i.imgur.com/KlQweAC.jpg',
                                                   'page_url': 'http://imgur.com/gallery/KlQweAC',
                                                   'thumbnail_url': 'http://i.imgur.com/KlQweACm.jpg'},
                                                  {'title': 'Studying the key terms in my police admin class when',
                                                   'image_url': 'http://i.imgur.com/qmHm43f.jpg',
                                                   'page_url': 'http://imgur.com/gallery/qmHm43f',
                                                   'thumbnail_url': 'http://i.imgur.com/qmHm43fm.jpg'},
                                                  {'title': 'This IKEA cat bed has everyone beat.',
                                                   'image_url': 'http://i.imgur.com/ETGB1BB.jpg',
                                                   'page_url': 'http://imgur.com/gallery/ETGB1BB',
                                                   'thumbnail_url': 'http://i.imgur.com/ETGB1BBm.jpg'}, {
                                                  'title': "10/10 - no more Aussie than this, you won't believe... etc etc",
                                                  'image_url': 'http://i.imgur.com/41u2Brb.jpg',
                                                  'page_url': 'http://imgur.com/gallery/41u2Brb',
                                                  'thumbnail_url': 'http://i.imgur.com/41u2Brbm.jpg'},
                                                  {'title': 'Pulled up to a red light today and...',
                                                   'image_url': 'http://i.imgur.com/3s0yIde.jpg',
                                                   'page_url': 'http://imgur.com/gallery/3s0yIde',
                                                   'thumbnail_url': 'http://i.imgur.com/3s0yIdem.jpg'},
                                                  {'title': 'Busted..', 'image_url': 'http://i.imgur.com/QuCdzQ8.jpg',
                                                   'page_url': 'http://imgur.com/gallery/QuCdzQ8',
                                                   'thumbnail_url': 'http://i.imgur.com/QuCdzQ8m.jpg'}, {
                                                  'title': 'The fear in her eyes... (Gezi Anniversary Protests, Taksim, Istanbul)',
                                                  'image_url': 'http://i.imgur.com/W2Fm9pt.jpg',
                                                  'page_url': 'http://imgur.com/gallery/W2Fm9pt',
                                                  'thumbnail_url': 'http://i.imgur.com/W2Fm9ptm.jpg'},
                                                  {'title': 'My wife bought me this and told me, "Results may vary."',
                                                   'image_url': 'http://i.imgur.com/I8LIun0.png',
                                                   'page_url': 'http://imgur.com/gallery/I8LIun0',
                                                   'thumbnail_url': 'http://i.imgur.com/I8LIun0m.png'},
                                                  {'title': 'The new Sprite logo',
                                                   'image_url': 'http://i.imgur.com/KI83nLf.jpg',
                                                   'page_url': 'http://imgur.com/gallery/KI83nLf',
                                                   'thumbnail_url': 'http://i.imgur.com/KI83nLfm.jpg'},
                                                  {'title': 'This is the moment I truly fell in love with Futurama.',
                                                   'image_url': 'http://i.imgur.com/SnS9FN5.jpg',
                                                   'page_url': 'http://imgur.com/gallery/SnS9FN5',
                                                   'thumbnail_url': 'http://i.imgur.com/SnS9FN5m.jpg'}, {
                                                  'title': 'There are trampolines built into the street in downtown Copenhagen.',
                                                  'image_url': 'http://i.imgur.com/rFbFBWY.jpg',
                                                  'page_url': 'http://imgur.com/gallery/rFbFBWY',
                                                  'thumbnail_url': 'http://i.imgur.com/rFbFBWYm.jpg'},
                                                  {'title': "Brush the cat my girlfriend said, it'll be fun she said.",
                                                   'image_url': 'http://i.imgur.com/oZwAgGX.jpg',
                                                   'page_url': 'http://imgur.com/gallery/oZwAgGX',
                                                   'thumbnail_url': 'http://i.imgur.com/oZwAgGXm.jpg'},
                                                  {'title': "This store's hours",
                                                   'image_url': 'http://i.imgur.com/w65tWZc.jpg',
                                                   'page_url': 'http://imgur.com/gallery/w65tWZc',
                                                   'thumbnail_url': 'http://i.imgur.com/w65tWZcm.jpg'},
                                                  {'title': 'Possibly the least manliest photo of me. Ever.',
                                                   'image_url': 'http://i.imgur.com/UGfM2I1.jpg',
                                                   'page_url': 'http://imgur.com/gallery/UGfM2I1',
                                                   'thumbnail_url': 'http://i.imgur.com/UGfM2I1m.jpg'}, {
                                                  'title': "She was born in my bedroom 7 years ago and we've had her ever since",
                                                  'image_url': 'http://i.imgur.com/lkZKmPk.jpg',
                                                  'page_url': 'http://imgur.com/gallery/lkZKmPk',
                                                  'thumbnail_url': 'http://i.imgur.com/lkZKmPkm.jpg'},
                                                  {'title': 'Ass so fine you could eat off of it',
                                                   'image_url': 'http://i.imgur.com/T1VhuBK.jpg',
                                                   'page_url': 'http://imgur.com/gallery/T1VhuBK',
                                                   'thumbnail_url': 'http://i.imgur.com/T1VhuBKm.jpg'},
                                                  {'title': 'I earned this!',
                                                   'image_url': 'http://i.imgur.com/sfOJnlM.jpg',
                                                   'page_url': 'http://imgur.com/gallery/sfOJnlM',
                                                   'thumbnail_url': 'http://i.imgur.com/sfOJnlMm.jpg'}, {
                                                  'title': 'The plate from the store brand rice lines up almost perfectly with the plate from the name brand rice.',
                                                  'image_url': 'http://i.imgur.com/Nuz3kjM.jpg',
                                                  'page_url': 'http://imgur.com/gallery/Nuz3kjM',
                                                  'thumbnail_url': 'http://i.imgur.com/Nuz3kjMm.jpg'}, {
                                                  'title': 'We just got a new kitten... Percy quickly decided who her new mother was',
                                                  'image_url': 'http://i.imgur.com/s6PxwP2.jpg',
                                                  'page_url': 'http://imgur.com/gallery/s6PxwP2',
                                                  'thumbnail_url': 'http://i.imgur.com/s6PxwP2m.jpg'}, {
                                                  'title': "A friend's son was disappointed when the tooth fairy hadn't arrived after three days...",
                                                  'image_url': 'http://i.imgur.com/A4P75wk.jpg',
                                                  'page_url': 'http://imgur.com/gallery/A4P75wk',
                                                  'thumbnail_url': 'http://i.imgur.com/A4P75wkm.jpg'}, {
                                                  'title': 'Girlfriend got me this after hearing my complaints of being exhausted after my first day at the gym.',
                                                  'image_url': 'http://i.imgur.com/JW7Kxfl.jpg',
                                                  'page_url': 'http://imgur.com/gallery/JW7Kxfl',
                                                  'thumbnail_url': 'http://i.imgur.com/JW7Kxflm.jpg'},
                                                  {'title': 'This bar has the best signs',
                                                   'image_url': 'http://i.imgur.com/y7l1oqC.jpg',
                                                   'page_url': 'http://imgur.com/gallery/y7l1oqC',
                                                   'thumbnail_url': 'http://i.imgur.com/y7l1oqCm.jpg'}, {
                                                  'title': 'I too have been waiting for this day! (girlfriend in the background)',
                                                  'image_url': 'http://i.imgur.com/TUc0Zry.jpg',
                                                  'page_url': 'http://imgur.com/gallery/TUc0Zry',
                                                  'thumbnail_url': 'http://i.imgur.com/TUc0Zrym.jpg'},
                                                  {'title': '.', 'image_url': 'http://i.imgur.com/vAiDd7h.jpg',
                                                   'page_url': 'http://imgur.com/gallery/vAiDd7h',
                                                   'thumbnail_url': 'http://i.imgur.com/vAiDd7hm.jpg'},
                                                  {'title': 'Privilege', 'image_url': 'http://i.imgur.com/w3ldggF.jpg',
                                                   'page_url': 'http://imgur.com/gallery/w3ldggF',
                                                   'thumbnail_url': 'http://i.imgur.com/w3ldggFm.jpg'},
                                                  {'title': 'Bought my cat a chair in IKEA',
                                                   'image_url': 'http://i.imgur.com/oG0LjBr.jpg',
                                                   'page_url': 'http://imgur.com/gallery/oG0LjBr',
                                                   'thumbnail_url': 'http://i.imgur.com/oG0LjBrm.jpg'},
                                                  {'title': 'That escalated quickly.',
                                                   'image_url': 'http://i.imgur.com/1L7P4FI.jpg',
                                                   'page_url': 'http://imgur.com/gallery/1L7P4FI',
                                                   'thumbnail_url': 'http://i.imgur.com/1L7P4FIm.jpg'}, {
                                                  'title': 'Official Pokémon Timeline Confirmed by Toshinobu Matsumiya, the Key Member and Scenario Director of Game Freak since R/S',
                                                  'image_url': 'http://i.imgur.com/pvba5Ur.png',
                                                  'page_url': 'http://imgur.com/gallery/pvba5Ur',
                                                  'thumbnail_url': 'http://i.imgur.com/pvba5Urm.png'},
                                                  {'title': 'Trailer Park Mansion',
                                                   'image_url': 'http://i.imgur.com/3QR8OQZ.jpg',
                                                   'page_url': 'http://imgur.com/gallery/3QR8OQZ',
                                                   'thumbnail_url': 'http://i.imgur.com/3QR8OQZm.jpg'}, {
                                                  'title': 'About a year ago I submitted a post about running 120-130mpw, last week I won the Canadian Marathon Championships!',
                                                  'image_url': 'http://i.imgur.com/1WuArnK.jpg',
                                                  'page_url': 'http://imgur.com/gallery/1WuArnK',
                                                  'thumbnail_url': 'http://i.imgur.com/1WuArnKm.jpg'},
                                                  {'title': 'The Dark Knight Formula',
                                                   'image_url': 'http://i.imgur.com/ll5PDlJ.jpg',
                                                   'page_url': 'http://imgur.com/gallery/ll5PDlJ',
                                                   'thumbnail_url': 'http://i.imgur.com/ll5PDlJm.jpg'}]

        # Pre-conditions

        # Execute code
        populator.populate()

        # Post-conditions
        self.assertEqual(self.MockFetchViralImages.call_count, 1)
        self.assertEqual(self.MockCursor.execute.call_count, 106)

    # Cleanup

    def test_ok_alt_db_connection(self):
        # Setup
        self.config['database'].pop('unix_socket', None)
        populator = imgur_populator.ImgurPopulator(self.config)

        # This sample data was pulled live from the Imgur API
        # It contains 104 "valid" images
        self.MockFetchViralImages.return_value = [{
                                                  'title': 'Nothing worse than waking up on a Sunday morning, and having to clean up the carnage left behind after another wild Saturday night.',
                                                  'image_url': 'http://i.imgur.com/2ttVNms.jpg',
                                                  'page_url': 'http://imgur.com/gallery/2ttVNms',
                                                  'thumbnail_url': 'http://i.imgur.com/2ttVNmsm.jpg'}, {
                                                  'title': "4.5 years after being told by a team of doctors that I'd probably never move anything below my shoulders again, I finally got to take this pic.",
                                                  'image_url': 'http://i.imgur.com/CB7eLyt.jpg',
                                                  'page_url': 'http://imgur.com/gallery/CB7eLyt',
                                                  'thumbnail_url': 'http://i.imgur.com/CB7eLytm.jpg'},
                                                  {'title': 'This is the end.',
                                                   'image_url': 'http://i.imgur.com/0tKpikW.jpg',
                                                   'page_url': 'http://imgur.com/gallery/0tKpikW',
                                                   'thumbnail_url': 'http://i.imgur.com/0tKpikWm.jpg'},
                                                  {'title': 'Way better than lemonade',
                                                   'image_url': 'http://i.imgur.com/AVBmbVi.jpg',
                                                   'page_url': 'http://imgur.com/gallery/AVBmbVi',
                                                   'thumbnail_url': 'http://i.imgur.com/AVBmbVim.jpg'},
                                                  {'title': 'The one who gets shot pays the bill.',
                                                   'image_url': 'http://i.imgur.com/sof10tP.jpg',
                                                   'page_url': 'http://imgur.com/gallery/sof10tP',
                                                   'thumbnail_url': 'http://i.imgur.com/sof10tPm.jpg'},
                                                  {'title': 'Lord, imagine the pizza this thing came with',
                                                   'image_url': 'http://i.imgur.com/tkeHnkn.jpg',
                                                   'page_url': 'http://imgur.com/gallery/tkeHnkn',
                                                   'thumbnail_url': 'http://i.imgur.com/tkeHnknm.jpg'},
                                                  {'title': '*groan*', 'image_url': 'http://i.imgur.com/OMqs78a.png',
                                                   'page_url': 'http://imgur.com/gallery/OMqs78a',
                                                   'thumbnail_url': 'http://i.imgur.com/OMqs78am.png'}, {
                                                  'title': 'Doing two weeks in Texas and got questioned about my "gang" tattoos at PT this morning.',
                                                  'image_url': 'http://i.imgur.com/xpmhVOY.jpg',
                                                  'page_url': 'http://imgur.com/gallery/xpmhVOY',
                                                  'thumbnail_url': 'http://i.imgur.com/xpmhVOYm.jpg'},
                                                  {'title': 'The best thing ever while growing up',
                                                   'image_url': 'http://i.imgur.com/4yLJnTd.jpg',
                                                   'page_url': 'http://imgur.com/gallery/4yLJnTd',
                                                   'thumbnail_url': 'http://i.imgur.com/4yLJnTdm.jpg'},
                                                  {'title': 'Other ways to say ...',
                                                   'image_url': 'http://i.imgur.com/6pR3YCO.jpg',
                                                   'page_url': 'http://imgur.com/gallery/6pR3YCO',
                                                   'thumbnail_url': 'http://i.imgur.com/6pR3YCOm.jpg'},
                                                  {'title': 'Men will be men',
                                                   'image_url': 'http://i.imgur.com/7QGD1S4.jpg',
                                                   'page_url': 'http://imgur.com/gallery/7QGD1S4',
                                                   'thumbnail_url': 'http://i.imgur.com/7QGD1S4m.jpg'},
                                                  {'title': 'Classic, A.',
                                                   'image_url': 'http://i.imgur.com/XsKUs0H.jpg',
                                                   'page_url': 'http://imgur.com/gallery/XsKUs0H',
                                                   'thumbnail_url': 'http://i.imgur.com/XsKUs0Hm.jpg'}, {
                                                  'title': 'You may remember Charlie the tortoise hibernating in the fridge? Well here he is enjoying summer after a successful escape from his bath..',
                                                  'image_url': 'http://i.imgur.com/6yfhiVV.jpg',
                                                  'page_url': 'http://imgur.com/gallery/6yfhiVV',
                                                  'thumbnail_url': 'http://i.imgur.com/6yfhiVVm.jpg'},
                                                  {'title': ' Tonight is the Night!',
                                                   'image_url': 'http://i.imgur.com/bc65yRi.png',
                                                   'page_url': 'http://imgur.com/gallery/bc65yRi',
                                                   'thumbnail_url': 'http://i.imgur.com/bc65yRim.png'},
                                                  {'title': 'This week in science',
                                                   'image_url': 'http://i.imgur.com/MY60SYK.png',
                                                   'page_url': 'http://imgur.com/gallery/MY60SYK',
                                                   'thumbnail_url': 'http://i.imgur.com/MY60SYKm.png'}, {
                                                  'title': 'We saved a turtle crossing the street. The turtle decided to thank us in a odd way.',
                                                  'image_url': 'http://i.imgur.com/VDOLVFd.jpg',
                                                  'page_url': 'http://imgur.com/gallery/VDOLVFd',
                                                  'thumbnail_url': 'http://i.imgur.com/VDOLVFdm.jpg'},
                                                  {'title': 'I\'m really enjoying "Astonishing X-Men" right now',
                                                   'image_url': 'http://i.imgur.com/ZfyhbA5.png',
                                                   'page_url': 'http://imgur.com/gallery/ZfyhbA5',
                                                   'thumbnail_url': 'http://i.imgur.com/ZfyhbA5m.png'}, {
                                                  'title': 'My friend took a photo of her house every 10 seconds for 2 hours the other evening. This was the result.',
                                                  'image_url': 'http://i.imgur.com/deqQyFV.jpg',
                                                  'page_url': 'http://imgur.com/gallery/deqQyFV',
                                                  'thumbnail_url': 'http://i.imgur.com/deqQyFVm.jpg'},
                                                  {'title': 'Hi, Imgur Team!',
                                                   'image_url': 'http://i.imgur.com/UvpwFEw.png',
                                                   'page_url': 'http://imgur.com/gallery/UvpwFEw',
                                                   'thumbnail_url': 'http://i.imgur.com/UvpwFEwm.png'}, {
                                                  'title': '"Chancho. When you are a man sometimes you wear stretchy pants in your room. It\'s for fun."',
                                                  'image_url': 'http://i.imgur.com/RAwKCqZ.jpg',
                                                  'page_url': 'http://imgur.com/gallery/RAwKCqZ',
                                                  'thumbnail_url': 'http://i.imgur.com/RAwKCqZm.jpg'},
                                                  {'title': 'Try me.', 'image_url': 'http://i.imgur.com/GdpRhn2.jpg',
                                                   'page_url': 'http://imgur.com/gallery/GdpRhn2',
                                                   'thumbnail_url': 'http://i.imgur.com/GdpRhn2m.jpg'},
                                                  {'title': 'These things happen.',
                                                   'image_url': 'http://i.imgur.com/ft0yvpD.jpg',
                                                   'page_url': 'http://imgur.com/gallery/ft0yvpD',
                                                   'thumbnail_url': 'http://i.imgur.com/ft0yvpDm.jpg'},
                                                  {'title': 'Trolling lvl. Turtle',
                                                   'image_url': 'http://i.imgur.com/T8lOlbI.jpg',
                                                   'page_url': 'http://imgur.com/gallery/T8lOlbI',
                                                   'thumbnail_url': 'http://i.imgur.com/T8lOlbIm.jpg'},
                                                  {'title': ' M&M color distribution',
                                                   'image_url': 'http://i.imgur.com/6XLv27D.jpg',
                                                   'page_url': 'http://imgur.com/gallery/6XLv27D',
                                                   'thumbnail_url': 'http://i.imgur.com/6XLv27Dm.jpg'},
                                                  {'title': 'Starting my New life as a Nanny',
                                                   'image_url': 'http://i.imgur.com/FyvegRR.jpg',
                                                   'page_url': 'http://imgur.com/gallery/FyvegRR',
                                                   'thumbnail_url': 'http://i.imgur.com/FyvegRRm.jpg'},
                                                  {'title': ' Happy Game of Thrones day, Internet!',
                                                   'image_url': 'http://i.imgur.com/Db9xTnm.jpg',
                                                   'page_url': 'http://imgur.com/gallery/Db9xTnm',
                                                   'thumbnail_url': 'http://i.imgur.com/Db9xTnmm.jpg'},
                                                  {'title': 'I found this little guy in my pool',
                                                   'image_url': 'http://i.imgur.com/FwspQsb.png',
                                                   'page_url': 'http://imgur.com/gallery/FwspQsb',
                                                   'thumbnail_url': 'http://i.imgur.com/FwspQsbm.png'}, {
                                                  'title': "A man begging for his wife's forgiveness inside Divorce Court. Chicago, 1948. ",
                                                  'image_url': 'http://i.imgur.com/1uxhBhm.jpg',
                                                  'page_url': 'http://imgur.com/gallery/1uxhBhm',
                                                  'thumbnail_url': 'http://i.imgur.com/1uxhBhmm.jpg'},
                                                  {'title': 'Ladies and Gentlemen, Stephen King,',
                                                   'image_url': 'http://i.imgur.com/L0UETbS.jpg',
                                                   'page_url': 'http://imgur.com/gallery/L0UETbS',
                                                   'thumbnail_url': 'http://i.imgur.com/L0UETbSm.jpg'}, {
                                                  'title': 'The teenage girls who were raped, murdered and left hanging from a mango tree in the case which has shocked India',
                                                  'image_url': 'http://i.imgur.com/91mhBIU.jpg',
                                                  'page_url': 'http://imgur.com/gallery/91mhBIU',
                                                  'thumbnail_url': 'http://i.imgur.com/91mhBIUm.jpg'},
                                                  {'title': 'Anyone looking for a job?',
                                                   'image_url': 'http://i.imgur.com/0fSzu6E.jpg',
                                                   'page_url': 'http://imgur.com/gallery/0fSzu6E',
                                                   'thumbnail_url': 'http://i.imgur.com/0fSzu6Em.jpg'},
                                                  {'title': '/fit/izen on fat people',
                                                   'image_url': 'http://i.imgur.com/8Qmq4d8.jpg',
                                                   'page_url': 'http://imgur.com/gallery/8Qmq4d8',
                                                   'thumbnail_url': 'http://i.imgur.com/8Qmq4d8m.jpg'},
                                                  {'title': 'A prayer', 'image_url': 'http://i.imgur.com/Jw1rr3x.jpg',
                                                   'page_url': 'http://imgur.com/gallery/Jw1rr3x',
                                                   'thumbnail_url': 'http://i.imgur.com/Jw1rr3xm.jpg'}, {
                                                  'title': 'My friend was paid $1,000+ to shave her head. She donated the money to cancer research and donated the hair to make wigs for cancer patients!',
                                                  'image_url': 'http://i.imgur.com/rPJ9PMR.jpg',
                                                  'page_url': 'http://imgur.com/gallery/rPJ9PMR',
                                                  'thumbnail_url': 'http://i.imgur.com/rPJ9PMRm.jpg'},
                                                  {'title': 'Happy birthday to the great man!',
                                                   'image_url': 'http://i.imgur.com/q5PU1RJ.jpg',
                                                   'page_url': 'http://imgur.com/gallery/q5PU1RJ',
                                                   'thumbnail_url': 'http://i.imgur.com/q5PU1RJm.jpg'},
                                                  {'title': 'Golden Not Retrieving.',
                                                   'image_url': 'http://i.imgur.com/dBHYENI.jpg',
                                                   'page_url': 'http://imgur.com/gallery/dBHYENI',
                                                   'thumbnail_url': 'http://i.imgur.com/dBHYENIm.jpg'}, {
                                                  'title': ' My prediction of how Game of Thrones will end, based on current events',
                                                  'image_url': 'http://i.imgur.com/1wBaCnD.png',
                                                  'page_url': 'http://imgur.com/gallery/1wBaCnD',
                                                  'thumbnail_url': 'http://i.imgur.com/1wBaCnDm.png'},
                                                  {'title': 'Was watching Linus when...',
                                                   'image_url': 'http://i.imgur.com/ca2eARK.png',
                                                   'page_url': 'http://imgur.com/gallery/ca2eARK',
                                                   'thumbnail_url': 'http://i.imgur.com/ca2eARKm.png'},
                                                  {'title': 'Dads will understand...',
                                                   'image_url': 'http://i.imgur.com/VpOFmOi.jpg',
                                                   'page_url': 'http://imgur.com/gallery/VpOFmOi',
                                                   'thumbnail_url': 'http://i.imgur.com/VpOFmOim.jpg'},
                                                  {'title': 'Goddamn, I cried laughing at this.',
                                                   'image_url': 'http://i.imgur.com/kE7adyW.jpg',
                                                   'page_url': 'http://imgur.com/gallery/kE7adyW',
                                                   'thumbnail_url': 'http://i.imgur.com/kE7adyWm.jpg'}, {
                                                  'title': 'Just finished serving this great nation to arrive home and find out I can marry the man I spent the last 9 years with.',
                                                  'image_url': 'http://i.imgur.com/VZk60RR.jpg',
                                                  'page_url': 'http://imgur.com/gallery/VZk60RR',
                                                  'thumbnail_url': 'http://i.imgur.com/VZk60RRm.jpg'}, {
                                                  'title': "Steve Irwin and 'Harriet' the tortoise who died in 2006 at the age of 176. Harriet was a pet of Charles Darwin in 1835.",
                                                  'image_url': 'http://i.imgur.com/ZZOlAT6.jpg',
                                                  'page_url': 'http://imgur.com/gallery/ZZOlAT6',
                                                  'thumbnail_url': 'http://i.imgur.com/ZZOlAT6m.jpg'},
                                                  {'title': 'My Daughter at the Aquarium',
                                                   'image_url': 'http://i.imgur.com/wx5szcF.jpg',
                                                   'page_url': 'http://imgur.com/gallery/wx5szcF',
                                                   'thumbnail_url': 'http://i.imgur.com/wx5szcFm.jpg'},
                                                  {'title': '.', 'image_url': 'http://i.imgur.com/y7zMxJf.jpg',
                                                   'page_url': 'http://imgur.com/gallery/y7zMxJf',
                                                   'thumbnail_url': 'http://i.imgur.com/y7zMxJfm.jpg'},
                                                  {'title': "This is not a gif; it's just a moving picture",
                                                   'image_url': 'http://i.imgur.com/S4YPEKk.jpg',
                                                   'page_url': 'http://imgur.com/gallery/S4YPEKk',
                                                   'thumbnail_url': 'http://i.imgur.com/S4YPEKkm.jpg'}, {
                                                  'title': 'My foreign mom texted me "I saw Hog Hogun at Frankfurt airport and took a selfie with him"',
                                                  'image_url': 'http://i.imgur.com/FJmppW6.jpg',
                                                  'page_url': 'http://imgur.com/gallery/FJmppW6',
                                                  'thumbnail_url': 'http://i.imgur.com/FJmppW6m.jpg'},
                                                  {'title': 'I just had to look it up...',
                                                   'image_url': 'http://i.imgur.com/lt11a5r.png',
                                                   'page_url': 'http://imgur.com/gallery/lt11a5r',
                                                   'thumbnail_url': 'http://i.imgur.com/lt11a5rm.png'},
                                                  {'title': "Yup, it's that time of year again.",
                                                   'image_url': 'http://i.imgur.com/o2IMExa.jpg',
                                                   'page_url': 'http://imgur.com/gallery/o2IMExa',
                                                   'thumbnail_url': 'http://i.imgur.com/o2IMExam.jpg'},
                                                  {'title': 'Aztec Dancer',
                                                   'image_url': 'http://i.imgur.com/Ekawxi4.jpg',
                                                   'page_url': 'http://imgur.com/gallery/Ekawxi4',
                                                   'thumbnail_url': 'http://i.imgur.com/Ekawxi4m.jpg'},
                                                  {'title': 'This just popped up in my newsfeed',
                                                   'image_url': 'http://i.imgur.com/z60U290.jpg',
                                                   'page_url': 'http://imgur.com/gallery/z60U290',
                                                   'thumbnail_url': 'http://i.imgur.com/z60U290m.jpg'},
                                                  {'title': 'Bill Gates is an amazingly humble man',
                                                   'image_url': 'http://i.imgur.com/DTDsH0P.jpg',
                                                   'page_url': 'http://imgur.com/gallery/DTDsH0P',
                                                   'thumbnail_url': 'http://i.imgur.com/DTDsH0Pm.jpg'},
                                                  {'title': 'Found a perfect spot to escape the afternoon sun.',
                                                   'image_url': 'http://i.imgur.com/AMkMtfQ.jpg',
                                                   'page_url': 'http://imgur.com/gallery/AMkMtfQ',
                                                   'thumbnail_url': 'http://i.imgur.com/AMkMtfQm.jpg'},
                                                  {'title': 'B.I.T.C.H.', 'image_url': 'http://i.imgur.com/0OZOkos.jpg',
                                                   'page_url': 'http://imgur.com/gallery/0OZOkos',
                                                   'thumbnail_url': 'http://i.imgur.com/0OZOkosm.jpg'},
                                                  {'title': 'Weight loss journey so far. 308 lbs to 170 in 17 months',
                                                   'image_url': 'http://i.imgur.com/DriOdab.jpg',
                                                   'page_url': 'http://imgur.com/gallery/DriOdab',
                                                   'thumbnail_url': 'http://i.imgur.com/DriOdabm.jpg'},
                                                  {'title': 'Mr. Rogers', 'image_url': 'http://i.imgur.com/cMICmuq.jpg',
                                                   'page_url': 'http://imgur.com/gallery/cMICmuq',
                                                   'thumbnail_url': 'http://i.imgur.com/cMICmuqm.jpg'}, {
                                                  'title': 'I had to use the bathroom on our walk today, so Tucker got to go inside the ladies room for the first time.',
                                                  'image_url': 'http://i.imgur.com/b4pX9eQ.jpg',
                                                  'page_url': 'http://imgur.com/gallery/b4pX9eQ',
                                                  'thumbnail_url': 'http://i.imgur.com/b4pX9eQm.jpg'}, {
                                                  'title': 'She reminds you of Stuart? I think shes going for the Simple Jack look.',
                                                  'image_url': 'http://i.imgur.com/BIj9DdI.jpg',
                                                  'page_url': 'http://imgur.com/gallery/BIj9DdI',
                                                  'thumbnail_url': 'http://i.imgur.com/BIj9DdIm.jpg'},
                                                  {'title': 'Brazil', 'image_url': 'http://i.imgur.com/Ceh5Wrn.jpg',
                                                   'page_url': 'http://imgur.com/gallery/Ceh5Wrn',
                                                   'thumbnail_url': 'http://i.imgur.com/Ceh5Wrnm.jpg'}, {
                                                  'title': "UK garden center grows Britain's first black tomatoes which contains anthocyanins, an oxidant believed to help fight cancer, diabetes and obesity",
                                                  'image_url': 'http://i.imgur.com/9xLD8eT.jpg',
                                                  'page_url': 'http://imgur.com/gallery/9xLD8eT',
                                                  'thumbnail_url': 'http://i.imgur.com/9xLD8eTm.jpg'}, {
                                                  'title': 'Today, my 6 year old sister in law asked who the man with the little arms and legs was. Now I cannot unsee it.',
                                                  'image_url': 'http://i.imgur.com/dGiGD80.jpg',
                                                  'page_url': 'http://imgur.com/gallery/dGiGD80',
                                                  'thumbnail_url': 'http://i.imgur.com/dGiGD80m.jpg'},
                                                  {'title': 'Sent my husband to buy a baby shower gift bag. Dammit.',
                                                   'image_url': 'http://i.imgur.com/medDnz3.jpg',
                                                   'page_url': 'http://imgur.com/gallery/medDnz3',
                                                   'thumbnail_url': 'http://i.imgur.com/medDnz3m.jpg'}, {
                                                  'title': 'I caught a picture this tree trying to crawl into the water',
                                                  'image_url': 'http://i.imgur.com/VWnZ9Vb.jpg',
                                                  'page_url': 'http://imgur.com/gallery/VWnZ9Vb',
                                                  'thumbnail_url': 'http://i.imgur.com/VWnZ9Vbm.jpg'},
                                                  {'title': "Stinkin' racists...",
                                                   'image_url': 'http://i.imgur.com/lza3DGE.png',
                                                   'page_url': 'http://imgur.com/gallery/lza3DGE',
                                                   'thumbnail_url': 'http://i.imgur.com/lza3DGEm.png'},
                                                  {'title': 'Parents burn',
                                                   'image_url': 'http://i.imgur.com/5irbrwT.jpg',
                                                   'page_url': 'http://imgur.com/gallery/5irbrwT',
                                                   'thumbnail_url': 'http://i.imgur.com/5irbrwTm.jpg'},
                                                  {'title': 'And we wonder why no one visits us',
                                                   'image_url': 'http://i.imgur.com/WesPTUl.jpg',
                                                   'page_url': 'http://imgur.com/gallery/WesPTUl',
                                                   'thumbnail_url': 'http://i.imgur.com/WesPTUlm.jpg'}, {
                                                  'title': 'went to a katy perry concert, I think this was taken at the right time.',
                                                  'image_url': 'http://i.imgur.com/88Ag08s.jpg',
                                                  'page_url': 'http://imgur.com/gallery/88Ag08s',
                                                  'thumbnail_url': 'http://i.imgur.com/88Ag08sm.jpg'},
                                                  {'title': 'Welcome To Fabulous Las Vegas, Nevada!',
                                                   'image_url': 'http://i.imgur.com/OJfxY4H.jpg',
                                                   'page_url': 'http://imgur.com/gallery/OJfxY4H',
                                                   'thumbnail_url': 'http://i.imgur.com/OJfxY4Hm.jpg'},
                                                  {'title': 'Look at who I found on my hike today!',
                                                   'image_url': 'http://i.imgur.com/EWyYXAN.jpg',
                                                   'page_url': 'http://imgur.com/gallery/EWyYXAN',
                                                   'thumbnail_url': 'http://i.imgur.com/EWyYXANm.jpg'},
                                                  {'title': "She's a looker",
                                                   'image_url': 'http://i.imgur.com/bOORCMW.png',
                                                   'page_url': 'http://imgur.com/gallery/bOORCMW',
                                                   'thumbnail_url': 'http://i.imgur.com/bOORCMWm.png'}, {
                                                  'title': 'This is actually disgusting. Forcing a child who doesn’t know any better to do something just because you believe in it. No child should be made to wear Crocs in public please stop this.',
                                                  'image_url': 'http://i.imgur.com/41ba59I.jpg',
                                                  'page_url': 'http://imgur.com/gallery/41ba59I',
                                                  'thumbnail_url': 'http://i.imgur.com/41ba59Im.jpg'},
                                                  {'title': "I don't know man..",
                                                   'image_url': 'http://i.imgur.com/wbKQtLf.jpg',
                                                   'page_url': 'http://imgur.com/gallery/wbKQtLf',
                                                   'thumbnail_url': 'http://i.imgur.com/wbKQtLfm.jpg'}, {
                                                  'title': 'I started to shave my head and got about halfway done when my clippers died. I have to be somewhere in twenty minutes. I present to you the only hat that I own.',
                                                  'image_url': 'http://i.imgur.com/R1F95NA.jpg',
                                                  'page_url': 'http://imgur.com/gallery/R1F95NA',
                                                  'thumbnail_url': 'http://i.imgur.com/R1F95NAm.jpg'},
                                                  {'title': 'The rug in this bar is painted on.',
                                                   'image_url': 'http://i.imgur.com/dn88F4l.jpg',
                                                   'page_url': 'http://imgur.com/gallery/dn88F4l',
                                                   'thumbnail_url': 'http://i.imgur.com/dn88F4lm.jpg'},
                                                  {'title': 'Old but gold: the Huey Hog helicopter',
                                                   'image_url': 'http://i.imgur.com/sasDIKu.jpg',
                                                   'page_url': 'http://imgur.com/gallery/sasDIKu',
                                                   'thumbnail_url': 'http://i.imgur.com/sasDIKum.jpg'},
                                                  {'title': 'I finally figured out who miley reminds me of',
                                                   'image_url': 'http://i.imgur.com/6AQL6at.png',
                                                   'page_url': 'http://imgur.com/gallery/6AQL6at',
                                                   'thumbnail_url': 'http://i.imgur.com/6AQL6atm.png'},
                                                  {'title': 'So annoying...',
                                                   'image_url': 'http://i.imgur.com/KlQweAC.jpg',
                                                   'page_url': 'http://imgur.com/gallery/KlQweAC',
                                                   'thumbnail_url': 'http://i.imgur.com/KlQweACm.jpg'},
                                                  {'title': 'Studying the key terms in my police admin class when',
                                                   'image_url': 'http://i.imgur.com/qmHm43f.jpg',
                                                   'page_url': 'http://imgur.com/gallery/qmHm43f',
                                                   'thumbnail_url': 'http://i.imgur.com/qmHm43fm.jpg'},
                                                  {'title': 'This IKEA cat bed has everyone beat.',
                                                   'image_url': 'http://i.imgur.com/ETGB1BB.jpg',
                                                   'page_url': 'http://imgur.com/gallery/ETGB1BB',
                                                   'thumbnail_url': 'http://i.imgur.com/ETGB1BBm.jpg'}, {
                                                  'title': "10/10 - no more Aussie than this, you won't believe... etc etc",
                                                  'image_url': 'http://i.imgur.com/41u2Brb.jpg',
                                                  'page_url': 'http://imgur.com/gallery/41u2Brb',
                                                  'thumbnail_url': 'http://i.imgur.com/41u2Brbm.jpg'},
                                                  {'title': 'Pulled up to a red light today and...',
                                                   'image_url': 'http://i.imgur.com/3s0yIde.jpg',
                                                   'page_url': 'http://imgur.com/gallery/3s0yIde',
                                                   'thumbnail_url': 'http://i.imgur.com/3s0yIdem.jpg'},
                                                  {'title': 'Busted..', 'image_url': 'http://i.imgur.com/QuCdzQ8.jpg',
                                                   'page_url': 'http://imgur.com/gallery/QuCdzQ8',
                                                   'thumbnail_url': 'http://i.imgur.com/QuCdzQ8m.jpg'}, {
                                                  'title': 'The fear in her eyes... (Gezi Anniversary Protests, Taksim, Istanbul)',
                                                  'image_url': 'http://i.imgur.com/W2Fm9pt.jpg',
                                                  'page_url': 'http://imgur.com/gallery/W2Fm9pt',
                                                  'thumbnail_url': 'http://i.imgur.com/W2Fm9ptm.jpg'},
                                                  {'title': 'My wife bought me this and told me, "Results may vary."',
                                                   'image_url': 'http://i.imgur.com/I8LIun0.png',
                                                   'page_url': 'http://imgur.com/gallery/I8LIun0',
                                                   'thumbnail_url': 'http://i.imgur.com/I8LIun0m.png'},
                                                  {'title': 'The new Sprite logo',
                                                   'image_url': 'http://i.imgur.com/KI83nLf.jpg',
                                                   'page_url': 'http://imgur.com/gallery/KI83nLf',
                                                   'thumbnail_url': 'http://i.imgur.com/KI83nLfm.jpg'},
                                                  {'title': 'This is the moment I truly fell in love with Futurama.',
                                                   'image_url': 'http://i.imgur.com/SnS9FN5.jpg',
                                                   'page_url': 'http://imgur.com/gallery/SnS9FN5',
                                                   'thumbnail_url': 'http://i.imgur.com/SnS9FN5m.jpg'}, {
                                                  'title': 'There are trampolines built into the street in downtown Copenhagen.',
                                                  'image_url': 'http://i.imgur.com/rFbFBWY.jpg',
                                                  'page_url': 'http://imgur.com/gallery/rFbFBWY',
                                                  'thumbnail_url': 'http://i.imgur.com/rFbFBWYm.jpg'},
                                                  {'title': "Brush the cat my girlfriend said, it'll be fun she said.",
                                                   'image_url': 'http://i.imgur.com/oZwAgGX.jpg',
                                                   'page_url': 'http://imgur.com/gallery/oZwAgGX',
                                                   'thumbnail_url': 'http://i.imgur.com/oZwAgGXm.jpg'},
                                                  {'title': "This store's hours",
                                                   'image_url': 'http://i.imgur.com/w65tWZc.jpg',
                                                   'page_url': 'http://imgur.com/gallery/w65tWZc',
                                                   'thumbnail_url': 'http://i.imgur.com/w65tWZcm.jpg'},
                                                  {'title': 'Possibly the least manliest photo of me. Ever.',
                                                   'image_url': 'http://i.imgur.com/UGfM2I1.jpg',
                                                   'page_url': 'http://imgur.com/gallery/UGfM2I1',
                                                   'thumbnail_url': 'http://i.imgur.com/UGfM2I1m.jpg'}, {
                                                  'title': "She was born in my bedroom 7 years ago and we've had her ever since",
                                                  'image_url': 'http://i.imgur.com/lkZKmPk.jpg',
                                                  'page_url': 'http://imgur.com/gallery/lkZKmPk',
                                                  'thumbnail_url': 'http://i.imgur.com/lkZKmPkm.jpg'},
                                                  {'title': 'Ass so fine you could eat off of it',
                                                   'image_url': 'http://i.imgur.com/T1VhuBK.jpg',
                                                   'page_url': 'http://imgur.com/gallery/T1VhuBK',
                                                   'thumbnail_url': 'http://i.imgur.com/T1VhuBKm.jpg'},
                                                  {'title': 'I earned this!',
                                                   'image_url': 'http://i.imgur.com/sfOJnlM.jpg',
                                                   'page_url': 'http://imgur.com/gallery/sfOJnlM',
                                                   'thumbnail_url': 'http://i.imgur.com/sfOJnlMm.jpg'}, {
                                                  'title': 'The plate from the store brand rice lines up almost perfectly with the plate from the name brand rice.',
                                                  'image_url': 'http://i.imgur.com/Nuz3kjM.jpg',
                                                  'page_url': 'http://imgur.com/gallery/Nuz3kjM',
                                                  'thumbnail_url': 'http://i.imgur.com/Nuz3kjMm.jpg'}, {
                                                  'title': 'We just got a new kitten... Percy quickly decided who her new mother was',
                                                  'image_url': 'http://i.imgur.com/s6PxwP2.jpg',
                                                  'page_url': 'http://imgur.com/gallery/s6PxwP2',
                                                  'thumbnail_url': 'http://i.imgur.com/s6PxwP2m.jpg'}, {
                                                  'title': "A friend's son was disappointed when the tooth fairy hadn't arrived after three days...",
                                                  'image_url': 'http://i.imgur.com/A4P75wk.jpg',
                                                  'page_url': 'http://imgur.com/gallery/A4P75wk',
                                                  'thumbnail_url': 'http://i.imgur.com/A4P75wkm.jpg'}, {
                                                  'title': 'Girlfriend got me this after hearing my complaints of being exhausted after my first day at the gym.',
                                                  'image_url': 'http://i.imgur.com/JW7Kxfl.jpg',
                                                  'page_url': 'http://imgur.com/gallery/JW7Kxfl',
                                                  'thumbnail_url': 'http://i.imgur.com/JW7Kxflm.jpg'},
                                                  {'title': 'This bar has the best signs',
                                                   'image_url': 'http://i.imgur.com/y7l1oqC.jpg',
                                                   'page_url': 'http://imgur.com/gallery/y7l1oqC',
                                                   'thumbnail_url': 'http://i.imgur.com/y7l1oqCm.jpg'}, {
                                                  'title': 'I too have been waiting for this day! (girlfriend in the background)',
                                                  'image_url': 'http://i.imgur.com/TUc0Zry.jpg',
                                                  'page_url': 'http://imgur.com/gallery/TUc0Zry',
                                                  'thumbnail_url': 'http://i.imgur.com/TUc0Zrym.jpg'},
                                                  {'title': '.', 'image_url': 'http://i.imgur.com/vAiDd7h.jpg',
                                                   'page_url': 'http://imgur.com/gallery/vAiDd7h',
                                                   'thumbnail_url': 'http://i.imgur.com/vAiDd7hm.jpg'},
                                                  {'title': 'Privilege', 'image_url': 'http://i.imgur.com/w3ldggF.jpg',
                                                   'page_url': 'http://imgur.com/gallery/w3ldggF',
                                                   'thumbnail_url': 'http://i.imgur.com/w3ldggFm.jpg'},
                                                  {'title': 'Bought my cat a chair in IKEA',
                                                   'image_url': 'http://i.imgur.com/oG0LjBr.jpg',
                                                   'page_url': 'http://imgur.com/gallery/oG0LjBr',
                                                   'thumbnail_url': 'http://i.imgur.com/oG0LjBrm.jpg'},
                                                  {'title': 'That escalated quickly.',
                                                   'image_url': 'http://i.imgur.com/1L7P4FI.jpg',
                                                   'page_url': 'http://imgur.com/gallery/1L7P4FI',
                                                   'thumbnail_url': 'http://i.imgur.com/1L7P4FIm.jpg'}, {
                                                  'title': 'Official Pokémon Timeline Confirmed by Toshinobu Matsumiya, the Key Member and Scenario Director of Game Freak since R/S',
                                                  'image_url': 'http://i.imgur.com/pvba5Ur.png',
                                                  'page_url': 'http://imgur.com/gallery/pvba5Ur',
                                                  'thumbnail_url': 'http://i.imgur.com/pvba5Urm.png'},
                                                  {'title': 'Trailer Park Mansion',
                                                   'image_url': 'http://i.imgur.com/3QR8OQZ.jpg',
                                                   'page_url': 'http://imgur.com/gallery/3QR8OQZ',
                                                   'thumbnail_url': 'http://i.imgur.com/3QR8OQZm.jpg'}, {
                                                  'title': 'About a year ago I submitted a post about running 120-130mpw, last week I won the Canadian Marathon Championships!',
                                                  'image_url': 'http://i.imgur.com/1WuArnK.jpg',
                                                  'page_url': 'http://imgur.com/gallery/1WuArnK',
                                                  'thumbnail_url': 'http://i.imgur.com/1WuArnKm.jpg'},
                                                  {'title': 'The Dark Knight Formula',
                                                   'image_url': 'http://i.imgur.com/ll5PDlJ.jpg',
                                                   'page_url': 'http://imgur.com/gallery/ll5PDlJ',
                                                   'thumbnail_url': 'http://i.imgur.com/ll5PDlJm.jpg'}]

        # Pre-conditions

        # Execute code
        populator.populate()

        # Post-conditions
        self.assertEqual(self.MockFetchViralImages.call_count, 1)
        self.assertEqual(self.MockCursor.execute.call_count, 106)

    # Cleanup

    def test_api_error(self):
        # Setup
        populator = imgur_populator.ImgurPopulator(self.config)
        self.MockFetchViralImages.return_value = []

        # Pre-conditions

        # Execute code
        populator.populate()

        # Post-conditions
        self.assertEqual(self.MockFetchViralImages.call_count, 1)
        self.assertEqual(self.MockCursor.execute.call_count, 0)

    # Cleanup

    def test_db_down(self):
        # Setup
        populator = imgur_populator.ImgurPopulator(self.config)
        self.MockDatabase.side_effect = mysql.connector.errors.InterfaceError()

        # Pre-conditions

        # Execute code
        populator.populate()

        # Post-conditions
        self.assertEqual(self.MockFetchViralImages.call_count, 1)
        self.assertEqual(self.MockCursor.execute.call_count, 0)

        # Cleanup
